export const dataCourses = [
  {
    _id: "642b5c79783e0b0fede8c7da",
    title: "Introduction to Python",
    description:
      "Learn the basics of Python programming language and start your journey as a developer!",
    img: "https://example.com/python.jpg",
    category: "school",
    type: "online",
    price: 99.99,
    hours: 20,
    certificate: false,
    subscribe: false,
    students: [],
    waitlist: [],
    __v: 0,
    count: 0,
    total: 0,
  },
  {
    _id: "642b5c7a783e0b0fede8c7dd",
    title: "Photography for Beginners",
    description:
      "Master the art of photography with this comprehensive course for beginners!",
    img: "https://example.com/photography.jpg",
    category: "university",
    type: "on site",
    price: 149.99,
    hours: 30,
    certificate: true,
    subscribe: false,
    students: [],
    waitlist: [],
    __v: 0,
  },
  {
    _id: "642b5c7a783e0b0fede8c7df",
    title: "Digital Marketing Fundamentals",
    description:
      "Learn the core concepts and strategies of digital marketing and boost your online presence!",
    img: "https://example.com/digital-marketing.jpg",
    category: "language",
    type: "online",
    price: 199.99,
    hours: 40,
    certificate: true,
    subscribe: false,
    students: [],
    waitlist: [],
    __v: 0,
  },
  {
    _id: "642b5d3293fd7d5a3fb99c29",
    title: "Introduction to Python",
    description:
      "Learn the basics of Python programming language and start your journey as a developer!",
    img: "https://example.com/python.jpg",
    category: "language",
    type: "online",
    price: 99.99,
    hours: 20,
    certificate: true,
    subscribe: true,
    students: [
      {
        username: "John Doe",
        googleId: "1234567890",
        email: "johndoe@example.com",
        role: "student",
        img: "https://example.com/johndoe.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "Bachelor's degree",
        phone: "123-456-7890",
        address: "123 Main St, Anytown USA",
        dateOfBirth: "1990-01-01T00:00:00.000Z",
      },
      {
        username: "Jane Smith",
        googleId: "0987654321",
        email: "janesmith@example.com",
        role: "student",
        img: "https://example.com/janesmith.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "Master's degree",
        phone: "555-555-5555",
        address: "456 Broadway, Anytown USA",
        dateOfBirth: "1995-05-05T00:00:00.000Z",
      },
    ],
    waitlist: [],
    __v: 0,
  },
  {
    _id: "642b5d3493fd7d5a3fb99c2c",
    title: "Photography for Beginners",
    description:
      "Master the art of photography with this comprehensive course for beginners!",
    img: "https://example.com/photography.jpg",
    category: "language",
    type: "on site",
    price: 149.99,
    hours: 30,
    certificate: true,
    subscribe: true,
    students: [
      {
        username: "Alice Jones",
        googleId: "abcdefghij",
        email: "alicejones@example.com",
        role: "student",
        img: "https://example.com/alicejones.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "High school diploma",
        phone: "555-123-4567",
        address: "789 Main St, Anytown USA",
        dateOfBirth: "2000-12-31T00:00:00.000Z",
      },
    ],
    waitlist: [],
    __v: 0,
  },
  {
    _id: "642b5d3493fd7d5a3fb99c2e",
    title: "Digital Marketing Fundamentals",
    description:
      "Learn the core concepts and strategies of digital marketing and boost your online presence!",
    img: "https://example.com/digital-marketing.jpg",
    category: "Business",
    type: "online",
    price: 199.99,
    hours: 40,
    certificate: true,
    subscribe: true,
    students: [
      {
        username: "Bob Johnson",
        googleId: "ijklmnopqr",
        email: "bobjohnson@example.com",
        role: "student",
        img: "https://example.com/bobjohnson.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "Associate's degree",
        phone: "555-987-6543",
      },
    ],
    waitlist: [],
    __v: 0,
  },
  {
    _id: "642b5da8648064dce44e3475",
    title: "Introduction to Python",
    description:
      "Learn the basics of Python programming language and start your journey as a developer!",
    img: "https://example.com/python.jpg",
    category: "Programming",
    type: "online",
    price: 99.99,
    hours: 20,
    certificate: true,
    subscribe: true,
    students: [
      {
        username: "John Doe",
        googleId: "1234567890",
        email: "johndoe@example.com",
        role: "student",
        img: "https://example.com/johndoe.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "Bachelor's degree",
        phone: "123-456-7890",
        address: "123 Main St, Anytown USA",
        dateOfBirth: "1990-01-01T00:00:00.000Z",
      },
      {
        username: "Jane Smith",
        googleId: "0987654321",
        email: "janesmith@example.com",
        role: "student",
        img: "https://example.com/janesmith.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "Master's degree",
        phone: "555-555-5555",
        address: "456 Broadway, Anytown USA",
        dateOfBirth: "1995-05-05T00:00:00.000Z",
      },
    ],
    waitlist: [],
    teacher: null,
    __v: 0,
  },
  {
    _id: "642b5da9648064dce44e3478",
    title: "Photography for Beginners",
    description:
      "Master the art of photography with this comprehensive course for beginners!",
    img: "https://example.com/photography.jpg",
    category: "Arts",
    type: "on site",
    price: 149.99,
    hours: 30,
    certificate: true,
    subscribe: true,
    students: [
      {
        username: "Alice Jones",
        googleId: "abcdefghij",
        email: "alicejones@example.com",
        role: "student",
        img: "https://example.com/alicejones.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "High school diploma",
        phone: "555-123-4567",
        address: "789 Main St, Anytown USA",
        dateOfBirth: "2000-12-31T00:00:00.000Z",
      },
    ],
    waitlist: [],
    teacher: null,
    __v: 0,
  },
  {
    _id: "642b5da9648064dce44e347a",
    title: "Digital Marketing Fundamentals",
    description:
      "Learn the core concepts and strategies of digital marketing and boost your online presence!",
    img: "https://example.com/digital-marketing.jpg",
    category: "Business",
    type: "online",
    price: 199.99,
    hours: 40,
    certificate: true,
    subscribe: true,
    students: [
      {
        username: "Bob Johnson",
        googleId: "ijklmnopqr",
        email: "bobjohnson@example.com",
        role: "student",
        img: "https://example.com/bobjohnson.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "Associate's degree",
        phone: "555-987-6543",
      },
    ],
    waitlist: [],
    teacher: null,
    __v: 0,
  },
  {
    _id: "642b5dcb2176e5c5782d532b",
    title: "Introduction to Python",
    description:
      "Learn the basics of Python programming language and start your journey as a developer!",
    img: "https://example.com/python.jpg",
    category: "Programming",
    type: "online",
    price: 99.99,
    hours: 20,
    certificate: true,
    subscribe: true,
    students: [
      {
        username: "John Doe",
        googleId: "1234567890",
        email: "johndoe@example.com",
        role: "student",
        img: "https://example.com/johndoe.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "Bachelor's degree",
        phone: "123-456-7890",
        address: "123 Main St, Anytown USA",
        dateOfBirth: "1990-01-01T00:00:00.000Z",
      },
      {
        username: "Jane Smith",
        googleId: "0987654321",
        email: "janesmith@example.com",
        role: "student",
        img: "https://example.com/janesmith.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "Master's degree",
        phone: "555-555-5555",
        address: "456 Broadway, Anytown USA",
        dateOfBirth: "1995-05-05T00:00:00.000Z",
      },
    ],
    waitlist: [],
    __v: 0,
  },
  {
    _id: "642b5dcc2176e5c5782d532e",
    title: "Photography for Beginners",
    description:
      "Master the art of photography with this comprehensive course for beginners!",
    img: "https://example.com/photography.jpg",
    category: "Arts",
    type: "on site",
    price: 149.99,
    hours: 30,
    certificate: true,
    subscribe: true,
    students: [
      {
        username: "Alice Jones",
        googleId: "abcdefghij",
        email: "alicejones@example.com",
        role: "student",
        img: "https://example.com/alicejones.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "High school diploma",
        phone: "555-123-4567",
        address: "789 Main St, Anytown USA",
        dateOfBirth: "2000-12-31T00:00:00.000Z",
      },
    ],
    waitlist: [],
    __v: 0,
  },
  {
    _id: "642b5dcc2176e5c5782d5330",
    title: "Digital Marketing Fundamentals",
    description:
      "Learn the core concepts and strategies of digital marketing and boost your online presence!",
    img: "https://example.com/digital-marketing.jpg",
    category: "Business",
    type: "online",
    price: 199.99,
    hours: 40,
    certificate: true,
    subscribe: true,
    students: [
      {
        username: "Bob Johnson",
        googleId: "ijklmnopqr",
        email: "bobjohnson@example.com",
        role: "student",
        img: "https://example.com/bobjohnson.jpg",
        appliedCourses: [],
        enrolledCourses: [],
        teachers: [],
        academicLevel: "Associate's degree",
        phone: "555-987-6543",
      },
    ],
    waitlist: [],
    __v: 0,
  },
];

export const detailsCourse = {
  _id: "642b5c79783e0b0fede8c7da",
  title: "Introduction to Python",
  description:
    "Learn the basics of Python programming language and start your journey as a developer!",
  img: "https://example.com/python.jpg",
  category: "Programming", //
  type: "online",
  price: 99.99,
  hours: 20,
  certificate: false, //
  subscribe: true,
  students: [],
  waitlist: [],
  __v: 0,
  //teacherName: "Amine Tabou",
  //duration:8,//weeks
  //timeWeek:4
  //program
};

export const dataTeacher = [
  {
    _id: "1",
    name: "amine",
    modules: ["arab", "Math", "Physics"],
    description:
      "My name is Professor Amine TOBNA, and I am a physics teacher with many years of experience in the field. I obtained my undergraduate and graduate degrees in physics from the University of Algiers and have since dedicated my career to teaching and inspiring the next generation of physicists.",
    courses: [dataCourses[1], dataCourses[2]],
  },
  {
    _id: "2",
    name: "Samy",
    modules: ["arab", "Math", "Physics"],
    description:
      "My name is Professor Amine TOBNA, and I am a physics teacher with many years of experience in the field. I obtained my undergraduate and graduate degrees in physics from the University of Algiers and have since dedicated my career to teaching and inspiring the next generation of physicists.",
    courses: [dataCourses[0], dataCourses[3]],
  },
  {
    _id: "3",
    name: "Karim",
    modules: ["algebre", "Math", "Physics"],
    description:
      "My name is Professor Amine TOBNA, and I am a physics teacher with many years of experience in the field. I obtained my undergraduate and graduate degrees in physics from the University of Algiers and have since dedicated my career to teaching and inspiring the next generation of physicists.",
    courses: [dataCourses[5], dataCourses[4]],
  },
];

export const detailsTeacher = {
  _id: "1",
  name: "amine",
  modules: ["arab", "Math", "Physics"],
  description:
    "My name is Professor Amine TOBNA, and I am a physics teacher with many years of experience in the field. I obtained my undergraduate and graduate degrees in physics from the University of Algiers and have since dedicated my career to teaching and inspiring the next generation of physicists.",
  courses: [dataCourses[1], dataCourses[2]]
};

export const comSoonImg = [
  "C:UserslenovoDesktopS4ProjetReactpublicimagescomming-soon-1.png",
  "C:UserslenovoDesktopS4ProjetReactpublicimagescomming-soon-2.png",
  "C:UserslenovoDesktopS4ProjetReactpublicimagescomming-soon-3.png",

];


export const homeTeachers = [dataTeacher[0], dataTeacher[2], dataTeacher[1]];